# Build settings

source: .
destination: ./_site
markdown: kramdown
# don't change the following; coderay will break the embedded
# annotations.
kramdown:
  enable_coderay: false
permalinks: pretty
safe: true
markdown_ext: md

##############################################################################

# Site settings

name: S1000 corpus annotation guidelines
homeurl: "https://katnastou.github.io/s1000-corpus-annotation-guidelines/"
editurl: "https://github.com/katnastou/s1000-corpus-annotation-guidelines/edit/master"
issueurl: "https://github.com/katnastou/s1000-corpus-annotation-guidelines/issues"

##############################################################################

# Collection settings

collections:
  entity:
    output: true
